# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('espresso_shots', models.PositiveIntegerField(default=1)),
                ('water', models.FloatField(default=100)),
                ('steamed_milk', models.BooleanField(default=False)),
                ('foam', models.FloatField(default=2)),
                ('extra_instructions', models.TextField(blank=True, null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bean')),
                ('powder', models.ManyToManyField(blank=True, to='main.Powder')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Roast')),
                ('syrup', models.ManyToManyField(blank=True, to='main.Syrup')),
            ],
        ),
    ]
